# Generated by Django 5.2.6 on 2025-09-27 23:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_min', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'services',
                'indexes': [models.Index(fields=['category'], name='ix_services_category')],
            },
        ),
        migrations.CreateModel(
            name='VendorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_links', to='services.service')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='vendors.vendor')),
            ],
            options={
                'db_table': 'vendor_service',
                'indexes': [models.Index(fields=['service'], name='ix_vendor_service_service')],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'service'), name='pk_vendor_service_pair')],
            },
        ),
    ]
