# Generated by Django 5.2.6 on 2025-11-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='duration_min',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='base_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='vendorservice',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
