# Generated by Django 5.2.6 on 2025-11-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_duration_min_service_duration_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='service',
            name='ix_services_category',
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['name'], name='ix_services_name'),
        ),
    ]
