# Generated by Django 5.2.6 on 2025-12-02 00:41

from django.db import migrations, models


def seed_services(apps, schema_editor):
    Service = apps.get_model("services", "Service")

    base_services = [
        {
            "name": "Oil Change",
            "description": "Replace engine oil and oil filter. Includes inspection for leaks and fluid levels.",
            "price": None,
            "duration": None,
            "is_active": True,
        },
        {
            "name": "Exterior Car Wash",
            "description": "Hand wash and dry exterior surfaces using microfiber towels and car-safe soap.",
            "price": None,
            "duration": None,
            "is_active": True,
        },
        {
            "name": "Interior Vacuum",
            "description": "Vacuum seats, floor mats, and trunk. Wipe down interior surfaces.",
            "price": None,
            "duration": None,
            "is_active": True,
        },
        {
            "name": "Combo Cleaning (Exterior + Interior)",
            "description": "Complete cleaning package: exterior wash plus interior vacuum and wipe down.",
            "price": None,
            "duration": None,
            "is_active": True,
        },
        {
            "name": "Headlight Restoration",
            "description": "Polish and restore clarity to headlights. Improves brightness and visibility at night.",
            "price": None,
            "duration": None,
            "is_active": True,
        },
        {
            "name": "A/C Refresher",
            "description": "A/C vent cleaning and odor treatment to improve air quality inside the car.",
            "price": None,
            "duration": None,
            "is_active": True,
        },
        {
            "name": "Windshield Wiper Replacement",
            "description": "Replace old windshield wipers for improved visibility in rain or snow.",
            "price": None,
            "duration": None,
            "is_active": True,
        },
        {
            "name": "Battery Replacement",
            "description": "Replace car battery and test charging system. Battery not included.",
            "price": None,
            "duration": None,
            "is_active": True,
        },
        {
            "name": "Engine Diagnostic Scan",
            "description": "Scan the engine with OBD-II to check warning lights or performance issues. Includes code report.",
            "price": None,
            "duration": None,
            "is_active": True,
        },
    ]

    for item in base_services:
        Service.objects.update_or_create(
            name=item["name"],
            defaults={
                "description": item["description"],
                "price": item["price"],
                "duration": item["duration"],
                "is_active": item["is_active"],
            },
        )


def unseed_services(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    names = [
        "Oil Change",
        "Exterior Car Wash",
        "Interior Vacuum",
        "Combo Cleaning (Exterior + Interior)",
        "Headlight Restoration",
        "A/C Refresher",
        "Windshield Wiper Replacement",
        "Battery Replacement",
        "Engine Diagnostic Scan",
    ]
    Service.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_alter_service_duration_alter_service_price"),  
    ]

    operations = [
        migrations.RunPython(seed_services, reverse_code=unseed_services),
    ]
