# Generated by Django 5.2.6 on 2025-09-27 23:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=200)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('formatted_address', models.CharField(blank=True, max_length=255)),
                ('place_id', models.CharField(blank=True, max_length=128)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='users.user')),
            ],
            options={
                'db_table': 'customers',
                'indexes': [models.Index(fields=['user'], name='uq_customers_user_idx'), models.Index(fields=['place_id'], name='ix_customers_place')],
            },
        ),
    ]
