# Generated by Django 5.2.6 on 2025-09-27 23:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('services', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_snapshot', models.CharField(blank=True, max_length=255)),
                ('address_place_id', models.CharField(blank=True, max_length=128)),
                ('address_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_long', models.DecimalField(blank=True, db_column='address_long', decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='vendors.vendor')),
            ],
            options={
                'db_table': 'bookings',
                'indexes': [models.Index(fields=['customer'], name='ix_bookings_customer'), models.Index(fields=['vendor'], name='ix_bookings_vendor'), models.Index(fields=['service'], name='ix_bookings_service'), models.Index(fields=['status'], name='ix_bookings_status')],
            },
        ),
    ]
