# Generated by Django 5.2.6 on 2025-12-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('customers', '0001_initial'),
        ('services', '0007_seed_initial_services'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=32),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['vendor', 'start_time'], name='ix_bookings_vendor_start'),
        ),
    ]
