# Generated by Django 5.2.6 on 2025-12-04 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_end_time_booking_start_time_and_more'),
        ('customers', '0001_initial'),
        ('services', '0007_seed_initial_services'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='customers.customer')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='services.service')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='vendors.vendor')),
            ],
            options={
                'db_table': 'cart',
                'indexes': [models.Index(fields=['customer'], name='ix_cart_customer'), models.Index(fields=['vendor'], name='ix_cart_vendor'), models.Index(fields=['service'], name='ix_cart_service')],
            },
        ),
    ]
